### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by ezspot** [Munoon/CSGO-Rankme-Web-Interface-for-WordPress#1]
Hi, tryed your plugin. 

Don't get any settings in the panel on the left side.
Running Wordpress 5.2.1

**Comment by ezspot** [comment]
@Munoon

**Comment by Munoon** [comment]
@spot88 hi! Sorry for not answering for a long time, I have not seen your publication.
I just installed new Wordpress 5.2.1 with my plugin and everything works fine!
![Screenshot_1](https://user-images.githubusercontent.com/43534008/59156304-996dfa00-8aa1-11e9-9f41-4912ed124bfd.png)
Please, make shure that you have activated my plugin
![Screenshot_2](https://user-images.githubusercontent.com/43534008/59156313-bc98a980-8aa1-11e9-862a-8f100523b6ce.png)

Thanks for using it!

**Comment by ezspot** [comment]
Hi again, thank for reply. 

When i click "activate" under plugins -> "CSGO Rankme". 
I get this message: No Update Required - Your WordPress database is already up-to-date!

And when i get back, it's still not activated, i have tryed to remove it and add it again. 
Same thing.

Is there any error\logs i can read? It gives me nothing to work with. 
Does it depend on themes? Some don't work?

**Comment by Munoon** [comment]
@spot88, you may make reserve copy of your website (with database) and send it to me. I will set up your website on local host and try to find error.
The best way to make reserve slot of WordPress is to use [Duplicator](https://wordpress.org/plugins/duplicator/) plugin.

Error logs usually writing in folder, where located "public_html" folder with your website, but it depends on your hosting system and settings.

**Comment by LemonPAKA** [comment]
> Hi again, thank for reply.
> 
> When i click "activate" under plugins -> "CSGO Rankme".
> I get this message: No Update Required - Your WordPress database is already up-to-date!
> 
> And when i get back, it's still not activated, i have tryed to remove it and add it again.
> Same thing.
> 
> Is there any error\logs i can read? It gives me nothing to work with.
> Does it depend on themes? Some don't work?

same as you...

**Comment by Munoon** [comment]
@spot88 and @LemonPAKA, try to install using WordPress.org. In plugins page type “CSGO Rankme” and install plugin from “Munoon”.

**Comment by LemonPAKA** [comment]
> @spot88 and @LemonPAKA, try to install using WordPress.org. In plugins page type “CSGO Rankme” and install plugin from “Munoon”.

doesn't work

**Comment by Munoon** [comment]
@LemonPAKA I didnt have any info or somethig else? May you give me backup of your website, so i will try to do somethig...

**Comment by ezspot** [comment]
Still not working tryed even to downgrade to Wordpress 5.1.1 and your version 1.1
Same result.

**Comment by Munoon** [comment]
@spot88 I cant do anythig if you will not give me your backup. Our conversation is useless at the moment.

**Comment by ezspot** [comment]
@Munoon  - Try this. 
https://cloud.hagendata.no/index.php/s/GbHtX8ABBR29QQ5

let me know when you downloaded it.

**Comment by ezspot** [comment]
Progress?

**Comment by Munoon** [comment]
@spot88 sorry, forgot about this. I’m set notification, so I will download and check it tonight, please wait a bit...

**Comment by sharkymcdongles** [comment]
I tried this as well and get the same issue redirect to a page that says it is updating the database as described above. I am running it in a container tagged latest from dockerhub:

https://hub.docker.com/_/wordpress/?tab=tags

I don't see anything in the logs at all except this when I click activate:

```
172.19.0.2 - - [17/Jun/2019:13:28:34 +0000] "GET /favicon.ico HTTP/1.1" 200 216 "https://kuberwise.com/wp-admin/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
172.19.0.2 - - [17/Jun/2019:13:28:36 +0000] "GET /wp-admin/plugins.php?action=activate&plugin=csgo-rankme%2Fcsgo-rankme.php&plugin_status=all&paged=1&s&_wpnonce=bf176de279 HTTP/1.1" 302 639 "https://kuberwise.com/wp-admin/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
172.19.0.2 - - [17/Jun/2019:13:28:37 +0000] "GET /wp-admin/upgrade.php?_wp_http_referer=%2Fwp-admin%2Fplugins.php%3Faction%3Dactivate%26plugin%3Dcsgo-rankme%252Fcsgo-rankme.php%26plugin_status%3Dall%26paged%3D1%26s%26_wpnonce%3Dbf176de279 HTTP/1.1" 200 875 "https://kuberwise.com/wp-admin/plugins.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
172.19.0.2 - - [17/Jun/2019:13:28:37 +0000] "GET /favicon.ico HTTP/1.1" 200 216 "https://kuberwise.com/wp-admin/upgrade.php?_wp_http_referer=%2Fwp-admin%2Fplugins.php%3Faction%3Dactivate%26plugin%3Dcsgo-rankme%252Fcsgo-rankme.php%26plugin_status%3Dall%26paged%3D1%26s%26_wpnonce%3Dbf176de279" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
172.19.0.2 - - [17/Jun/2019:13:28:42 +0000] "GET / HTTP/1.1" 200 8284 "https://kuberwise.com/wp-admin/upgrade.php?_wp_http_referer=%2Fwp-admin%2Fplugins.php%3Faction%3Dactivate%26plugin%3Dcsgo-rankme%252Fcsgo-rankme.php%26plugin_status%3Dall%26paged%3D1%26s%26_wpnonce%3Dbf176de279" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
```

I tried it by uploading a zip manually first. I then deleted and tried via the portal thing a second time and same result.

**Comment by Munoon** [comment]
@spot88 this is not it.
![Screenshot_1](https://user-images.githubusercontent.com/43534008/59617694-7988a700-912f-11e9-86af-ecf2dc060ae6.png)

**Comment by ezspot** [comment]
@Munoon  - Try again. 
https://cloud.hagendata.no/index.php/s/CMpZLNd7Eywrgei

**Comment by Munoon** [comment]
@spot88 thank you. I have installed you website and tried to install my WordPress plugin. Everything works fine!
![Screenshot_1](https://user-images.githubusercontent.com/43534008/59659013-e2aeff80-91ad-11e9-88c5-1203447954aa.png)

**Comment by LemonPAKA** [comment]
@Munoon if I try to force activate the plugin by change setting in my database...when I try to enter admin panel I got this
![QQ截图20190618154918](https://user-images.githubusercontent.com/17202894/59663274-3e46b080-91e1-11e9-8a56-b1a27a8c90e1.png)
